services:
  - type: cron
    name: arbitrage-detector
    schedule: "*/15 * * * *"  # Every 15 minutes
    runtime: python
    plan: free
    buildCommand: ""
    startCommand: "python main.py"
    envVars:
      - key: ODDS_API_KEY
        sync: false
      - key: DISCORD_WEBHOOK_URL
        sync: false
